const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const pkg = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'),
);

const outPath = path.join(ROOT, 'src', 'environments', 'version.ts');
const content = `// Auto-generated by scripts/generate-version.js — do not edit
export const version = '${pkg.version}';
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);

console.log(`✅  version.ts actualizado a v${pkg.version}`);
